import type { Metadata } from "next";
import { Dancing_Script, Lexend } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { GridBackground } from "@/components/grid-background";
import { Header } from "@/components/header";
import { readRootLayout } from "@/data/layouts";

// FONTS -----------------------------------------------------------------------------------------------------------------------------------
const base = Lexend({ variable: "--font-base", subsets: ["latin"] });
const heading = Dancing_Script({ variable: "--font-heading", subsets: ["latin"], weight: ["700"] });

// METADATA --------------------------------------------------------------------------------------------------------------------------------
export const metadata: Metadata = {
  title: "@ec/nextjs",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  const { logoImg, navs, socials } = readRootLayout();

  return (
    <html lang="fr">
      {/* <head>
        <script src="https://unpkg.com/react-scan/dist/auto.global.js" />
      </head> */}
      <body className={`${base.variable} ${heading.variable} flex min-h-screen flex-col overflow-x-hidden antialiased`}>
        <GridBackground />
        <Header image={logoImg} navs={navs} socials={socials} />
        <main className="relative mt-20 flex-1 sm:mt-28 md:mt-40">{children}</main>
        <section className="relative flex justify-between bg-neutral-700 p-4 text-white">
          <span>© 2025 Eliana Corré</span>
          <Link href="#">Mentions légales</Link>
        </section>
      </body>
    </html>
  );
}
